import { Schema, model } from "mongoose";

const virtualChallengeSchema = new Schema({
  title: { type: String, required: true }, // Title generated by backend (e.g., "Show your weekend setup")
  description: { type: String }, // Description generated by backend (e.g., "Share your weekend setup photos")
  mediaType: { type: String, enum: ["photo", "video", "text"], required: true },
  startDate: { type: Date, required: true },
  endDate: { type: Date, required: true },
  visibility: { type: String, enum: ["public", "private"], default: "public" },
  status: {
    type: String,
    enum: ["active", "completed", "expired"],
    default: "active",
  },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

export default model("VirtualChallenge", virtualChallengeSchema);
